version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: uceconnect_db_local
    restart: unless-stopped
    environment:
      POSTGRES_DB: uceconnect
      POSTGRES_USER: uceconnect_user
      POSTGRES_PASSWORD: uceconnect_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - ./src/infrastructure/db/migrations:/docker-entrypoint-initdb.d
    networks:
      - uceconnect_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: uceconnect_backend_local
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    networks:
      - uceconnect_network

volumes:
  postgres_data_local:

networks:
  uceconnect_network:
    driver: bridge
